import db from '../config/db.js';

export const addInventoryBatch = async (req, res) => {
    try {

        // console.log(" Login in user name ", req.user);
        const { 
            // itemName, 
            officeName, 
            // quantity, 
            purchaseNo, 
            purchaseDate, 
            invoiceDate, 
            vendorId,
            // unitCost
            items:rawItems 
        } = req.body;

         const loggedInUserId = 
            req.user?.EmpId ||  // 🚀 Checks for EmpId wrapper matching your table schema format
            req.user?.id ||     // Checks for lowercase id variations
            req.user?.ID ||     // Checks for uppercase ID variations
            1;

        //  if (!purchaseNo || !purchaseNo.trim()) {
        //     return res.status(400).json({ 
        //         success: false, 
        //         message: "Validation Error: Purchase Order Number (PO) is strictly required." 
        //     });
        // }


        // if (!itemName || !officeName || !quantity) {
        //     return res.status(400).json({ 
        //         success: false, 
        //         message: "Validation Error: Item Name, Target Office Name, and Quantity are required parameters." 
        //     });
        // }

        // const [officeProfile] = await db.query(
        //     'SELECT OfficeID FROM officemaster WHERE OfficeName = ? LIMIT 1',
        //     [officeName.trim()]
        // );


        // if (!officeName || !items || !Array.isArray(items) || items.length === 0) {
        //     return res.status(400).json({ 
        //         success: false, 
        //         message: "Validation Error: Target Office Name and at least one catalog item line are required." 
        //     });
        // }


        if (!officeName || !rawItems) {
            return res.status(400).json({ 
                success: false, 
                message: "Validation Error: Target Office Name and item payload lines are required." 
            });
        }

        // 🚀 2. SAFE FORM-DATA ARRAY PARSER ENGINE
        let items = [];
        try {
            items = typeof rawItems === 'string' ? JSON.parse(rawItems) : rawItems;
        } catch (parseErr) {
            return res.status(400).json({ success: false, message: "Malformed items payload structure data formatting." });
        }

        // Final safe check array type validation wrapper guard
        if (!Array.isArray(items) || items.length === 0) {
            return res.status(400).json({ 
                success: false, 
                message: "Validation Error: At least one catalog item line must be provided." 
            });
        }

         const [officeProfile] = await db.query(
                'SELECT ID FROM officemaster WHERE OfficeName = ? LIMIT 1',
                [officeName.trim()]
        );


        if (officeProfile.length === 0) {
            return res.status(404).json({ 
                success: false, 
                message: `Operational validation failed: Office designation "${officeName}" is not registered in the system index.` 
            });
        }

        //  const resolvedOfficeId = officeProfile[0].OfficeID;

        const resolvedOfficeId = officeProfile[0].ID;

        // Capture uploaded server storage path strings generated by Multer
        const purchasePdfPath = req.files && req.files['purchaseCopy'] ? req.files['purchaseCopy'][0].path : null;
        const invoicePdfPath = req.files && req.files['invoiceCopy'] ? req.files['invoiceCopy'][0].path : null;
        // await db.query(
        //     'INSERT IGNORE INTO itemmaster (name, category, Date) VALUES (?, ?, NOW())',
        //     [itemName.trim(), category.trim()]
        // );

        for (const lineItem of items) {
            // Validate individual item row variables defensively
            if (!lineItem.itemName || !lineItem.quantity) {
                return res.status(400).json({
                    success: false,
                    message: "Validation Error: Complete Item Name and Quantity properties for each row entry."
                });
            }

        // Step B: Insert the complete tracking log row inside stockmaster
        await db.query(`
            INSERT INTO stockmaster 
                (officeId, item, Quantity,
                 source_type, purchase_no, purchase_date, purchase_pdf, invoice_date, invoice_pdf, unit_cost, vendorId, createdBy, UpdateDateTime) 
            VALUES (?, ?, ?, 'purchase', ?, ?, ?, ?, ?, ?, ?, ?, NOW())
        `, [
            resolvedOfficeId, 
            // itemName.trim(), 
             lineItem.itemName.trim(),
            // parseInt(quantity) || 0, 
            parseInt(lineItem.quantity) || 0,
             purchaseNo.trim(),
            // purchaseNo || null, 
            purchaseDate || null, 
            purchasePdfPath,               // Correctly maps to purchase_pdf
            invoiceDate || null,           // Correctly maps to invoice_date
            invoicePdfPath,                // Correctly maps to invoice_pdf
            // parseFloat(unitCost || 0) || 0.00
            // purchaseNo.trim(),
             
            parseFloat(lineItem.unitCost || 0) || 0.00,
             vendorId ? parseInt(vendorId) : null,
            loggedInUserId

        ]);
    }

        return res.status(201).json({ success: true, message: "Stock consignment logged and paper-trail archived successfully!" });
    } catch (error) {
        return res.status(500).json({ success: false, message: "Failed to record stock consignment arrival.", error: error.message });
    }
};


 export const updateInventoryItem = async (req, res) => {
    // const { id, name, category } = req.body;

    const { 
        id, 
        category, 
        officeId, 
        Quantity, 
        purchase_date, 
        purchase_pdf, 
        invoice_date, 
        invoice_pdf, 
        unit_cost 
    } = req.body;

    try {

        //  if (!id || !name || !category) {
        //     return res.status(400).json({
        //         success: false,
        //         message: "Validation Error: 'id', 'name', and 'category' are required parameters inside the JSON body."
        //     });
        // }

         if (!id) {
            return res.status(400).json({
                success: false,
                message: "Validation Error: 'id' index parameter is required inside the request body."
            });
        }

         // This ensures old attachments aren't wiped out if the user didn't pick a new file!
        let purchase_pdf_path = req.body.purchaseCopy || null;
        let invoice_pdf_path = req.body.invoiceCopy || null;


        // 🎯 MULTER PIPELINE ALIGNMENT: Check if fresh binary documents exist in the request
        if (req.files) {
            if (req.files['purchaseCopy']) {
                purchase_pdf_path = req.files['purchaseCopy'][0].path;
            }
            if (req.files['invoiceCopy']) {
                invoice_pdf_path = req.files['invoiceCopy'][0].path;
            }
        }


        // const [result] = await db.query(
        //     'UPDATE itemmaster SET name = ?, category = ? WHERE id = ?',
        //     [name.trim(), category.trim(), id]
        // );

         const [stockResult] = await db.query(
            `UPDATE stockmaster SET 
                officeId = ?, 
                Quantity = ?, 
                purchase_date = ?, 
                purchase_pdf = ?, 
                invoice_date = ?, 
                invoice_pdf = ?, 
                unit_cost = ?,
                UpdateDateTime = NOW()
             WHERE id = ?`,
            [
                officeId, 
                parseInt(Quantity) || 0, 
                purchase_date || null, 
                purchase_pdf_path,
                invoice_date || null, 
                invoice_pdf_path, 
                parseFloat(unit_cost) || 0.00, 
                id
            ]
        );

        // if (result.affectedRows === 0) {
        //     return res.status(404).json({ success: false, message: "Target product row index not found." });
        // }

         if (stockResult.affectedRows === 0) {
            return res.status(404).json({ success: false, message: "Target stockmaster registry entry not found." });
        }

         // 2. Safely look up the item name linked to this stock row to update its global category inside itemmaster
        const [stockRow] = await db.query('SELECT item FROM stockmaster WHERE id = ?', [id]);
        if (stockRow.length > 0 && category) {
            await db.query(
                'UPDATE itemmaster SET category = ? WHERE name = ?',
                [category.trim(), stockRow[0].item]
            );
        }

        return res.status(200).json({ success: true, message: "item Details updated successfully." });
    } catch (error) {
        return res.status(500).json({ success: false, message: "Failed to apply catalog modifications.", error: error.message });
    }
};



 export const getInventory = async (req, res) => {
    try {
        const page = parseInt(req.query.page) || 1;
        const limit = parseInt(req.query.limit) || 200;
        const offset = (page - 1) * limit;

        // const userRole = (req.user?.role || 'employee').toLowerCase();
        // const userOfficeId = req.user?.officeId || 'HQ';

        const userRole = (req.user?.role || req.headers['x-user-role'] || 'employee').toLowerCase();
        const userOfficeId = req.user?.officeId || req.headers['x-user-office-id'] || 1;

        let rowsQuery = '';
        let countQuery = '';
        let queryParams = [];
        let countParams = [];

        // Calculate totals for navigation metrics
        // const [countResult] = await db.query('SELECT COUNT(*) as total FROM itemmaster');
        // const totalRows = countResult[0].total;
        // const totalPages = Math.ceil(totalRows / limit);
         

        if (userRole === 'admin') {
            // A. Super Admin pulls a global master review of all stock allocations
            countQuery = 'SELECT COUNT(*) as total FROM stockmaster';
            countParams = [];

        //     rowsQuery = `
        //         SELECT 
        //             s.id as id, 
        //             s.item as item, 
        //             s.officeId as officeId, 
        //             s.Quantity as Quantity, 
        //             s.UpdateDateTime as UpdateDateTime,
        //             i.category as Category,
        //             o.OfficeName,
        //             s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost,
        //             e.EmpId as creatorEmployeeId,
        //             e.Name as creatorName,
        //             v.VendorName as vendorName,
        //             CASE 
        //                 WHEN s.purchase_no IS NULL OR s.purchase_no = '' OR s.purchase_no = '—' OR s.purchase_no = '-' 
        //                 THEN (
        //                     SELECT em.Name 
        //                     FROM stocktransfer st
        //                     LEFT JOIN employeemaster em ON st.FromOfficeID = em.OfficeCode OR em.ID = 1 -- Fallback chain matching origin
        //                     LEFT JOIN itemmaster im ON st.Item = im.id
        //                     WHERE im.name = s.item AND st.ToOfficeID = s.officeId AND st.Status = 'Accepted'
        //                     LIMIT 1
        //                 )
        //                 ELSE IFNULL(e.Name, 'Central Corporate')
        //             END as creatorName
        //         FROM stockmaster s
        //         LEFT JOIN itemmaster i ON s.item = i.name
        //         LEFT JOIN officemaster o ON s.officeId = o.ID
        //         LEFT JOIN employeemaster e ON s.createdBy = e.ID
        //         LEFT JOIN vendor v ON s.vendorId = v.VendorId
        //         ORDER BY s.id DESC
        //         LIMIT ? OFFSET ?
        //     `;
        //     queryParams = [limit, offset];
        // } else {
        //     // B. Branch Admins and Employees only fetch rows matching their officeId restriction
        //     countQuery = 'SELECT COUNT(*) as total FROM stockmaster WHERE officeId = ?';
        //     countParams = [userOfficeId];

        //     rowsQuery = `
        //         SELECT 
        //             s.id as id, 
        //             s.item as item, 
        //             s.officeId as officeId, 
        //             s.Quantity as Quantity, 
        //             s.UpdateDateTime as UpdateDateTime,
        //             i.category as Category,
        //             o.OfficeName,
        //             s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost,
        //              e.EmpId as creatorEmployeeId, 
                    
        //             v.VendorName as vendorName,
        //            CASE 
        //                 WHEN s.purchase_no IS NULL OR s.purchase_no = '' OR s.purchase_no = '—' OR s.purchase_no = '-' 
        //                 THEN (
        //                     SELECT em.Name 
        //                     FROM stocktransfer st
        //                     LEFT JOIN employeemaster em ON st.FromOfficeID = em.OfficeCode OR em.ID = 1
        //                     LEFT JOIN itemmaster im ON st.Item = im.id
        //                     WHERE im.name = s.item AND st.ToOfficeID = s.officeId AND st.Status = 'Accepted'
        //                     LIMIT 1
        //                 )
        //                 ELSE IFNULL(e.Name, 'Central Corporate')
        //             END as creatorName
        //         FROM stockmaster s
        //         LEFT JOIN itemmaster i ON s.item = i.name
        //          LEFT JOIN officemaster o ON s.officeId = o.ID
        //          LEFT JOIN employeemaster e ON s.createdBy = e.ID
        //         LEFT JOIN vendor v ON s.vendorId = v.VendorId
        //         WHERE s.officeId = ?
        //         ORDER BY s.id DESC
        //         LIMIT ? OFFSET ?
        //     `;
        //     queryParams = [userOfficeId, limit, offset];
        // }


        rowsQuery = `
                SELECT 
                    s.id as id, 
                    s.item as item, 
                    s.officeId as officeId, 
                    s.Quantity as Quantity, 
                    s.UpdateDateTime as UpdateDateTime,
                    i.category as Category,
                     s.source_type,
                    o.OfficeName,
                    s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost,
                    e.EmpId as creatorEmployeeId,
                    e.Name as creatorName,
                    v.VendorName as vendorName,
                    
                    /* 🎯 PRESERVED LOGIC: Safely returns the user's name without crashing if purchase_no is custom text */
                    CASE 
                        WHEN s.purchase_no IS NULL OR s.purchase_no = '' OR s.purchase_no = '—' OR s.purchase_no = '-' 
                        THEN 'Central Corporate'
                        ELSE IFNULL(e.Name, 'Central Corporate')
                    END as creatorName
                FROM stockmaster s
                LEFT JOIN itemmaster i ON s.item = i.name
                LEFT JOIN officemaster o ON s.officeId = o.ID
                LEFT JOIN employeemaster e ON s.createdBy = e.ID
                LEFT JOIN vendor v ON s.vendorId = v.VendorId
                
                ORDER BY s.id DESC
                LIMIT ? OFFSET ?
            `;
            queryParams = [limit, offset];
        } else {
            // B. Branch Admins and Employees only fetch purchase rows matching their officeId restriction
            // 🎯 FIXED: Count only rows with source_type = 'purchase' for this branch
            countQuery = "SELECT COUNT(*) as total FROM stockmaster WHERE officeId = ?";
            countParams = [userOfficeId];

            rowsQuery = `
                SELECT 
                    s.id as id, 
                    s.item as item, 
                    s.officeId as officeId, 
                    s.Quantity as Quantity, 
                    s.UpdateDateTime as UpdateDateTime,
                    i.category as Category,
                     s.source_type,
                    o.OfficeName,
                    s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost,
                    e.EmpId as creatorEmployeeId, 
                    v.VendorName as vendorName,
                    
                    /* 🎯 PRESERVED LOGIC: Safely returns the user's name without crashing if purchase_no is custom text */
                    CASE 
                        WHEN s.purchase_no IS NULL OR s.purchase_no = '' OR s.purchase_no = '—' OR s.purchase_no = '-' 
                        THEN 'Central Corporate'
                        ELSE IFNULL(e.Name, 'Central Corporate')
                    END as creatorName
                FROM stockmaster s
                LEFT JOIN itemmaster i ON s.item = i.name
                LEFT JOIN officemaster o ON s.officeId = o.ID
                LEFT JOIN employeemaster e ON s.createdBy = e.ID
                LEFT JOIN vendor v ON s.vendorId = v.VendorId
                WHERE s.officeId = ? AND s.source_type = 'purchase'
                ORDER BY s.id DESC
                LIMIT ? OFFSET ?
            `;
            queryParams = [userOfficeId, limit, offset];
        }





        // 🛡️ Apply Dynamic SQL Join Filters Based On Security Hierarchy Roles
        // if (userRole === 'admin') {
        //     // Master Admin pulls a global comprehensive overview matching all branch locations
        //     rowsQuery = `
        //         SELECT 
        //             i.id as ItemId, i.name as ItemName, i.category as Category, i.Date as DateCreated,
        //             IFNULL(s.officeId, 'HQ') as officeId, IFNULL(s.Quantity, 0) as Quantity,
        //             s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost, s.UpdateDateTime
        //         FROM itemmaster i
        //         LEFT JOIN stockmaster s ON i.name = s.item
        //         ORDER BY i.id DESC
        //         LIMIT ? OFFSET ?
        //     `;
        //     queryParams = [limit, offset];
        // } else {
        //     // 🔒 Branch Admins and Employees only fetch mapped rows explicitly tied to their location strings
        //     rowsQuery = `
        //         SELECT 
        //             i.id as ItemId, i.name as ItemName, i.category as Category, i.Date as DateCreated,
        //             ? as officeId, IFNULL(s.Quantity, 0) as Quantity,
        //             s.purchase_no, s.purchase_date, s.purchase_pdf, s.invoice_date, s.invoice_pdf, s.unit_cost, s.UpdateDateTime
        //         FROM itemmaster i
        //         LEFT JOIN stockmaster s ON i.name = s.item AND s.officeId = ?
        //         ORDER BY i.id DESC
        //         LIMIT ? OFFSET ?
        //     `;
        //     queryParams = [userOfficeId, userOfficeId, limit, offset];
        // }

        const [countResult] = await db.query(countQuery, countParams);
        const totalRows = countResult[0].total;
        const totalPages = Math.ceil(totalRows / limit);

        const [rows] = await db.query(rowsQuery, queryParams);

        return res.status(200).json({
            success: true,
            data: rows,
            pagination: { currentPage: page, totalPages, totalRows }
        });
    } catch (error) {
        return res.status(500).json({ success: false, message: "Inventory streaming failure.", error: error.message });
    }
};

// export const issueInventoryAsset = async (req, res) => {
//     // 🎯 FIX: Updated keys to match your exact Postman casing (FromOfficeID, ToOfficeID)
//     const { 
//         issueType, 
//         itemName, 
//         qty, 
//         empId, 
//         empName, 
//         FromOfficeID,  
//         ToOfficeID,    
//         modeOfTransfer 
//     } = req.body;

//     // Assign variables based on your exact uppercase payload keys
//     const sourceOffice = FromOfficeID || 1;
//     const destinationOffice = ToOfficeID;

//     try {

//         // LOOKUP ITEM ID: Get the numeric ID from itemmaster
//         const [itemLookup] = await db.query('SELECT id FROM itemmaster WHERE name = ? LIMIT 1', [itemName]);
//         const itemId = itemLookup.length > 0 ? itemLookup[0].id : null;

//         // 🚨 ANTI-SELF-TRANSFER LOCK
//         if (parseInt(sourceOffice) === parseInt(destinationOffice) && issueType === 'branch') {
//             return res.status(400).json({
//                 success: false,
//                 message: "Validation Error: Origin branch (FromOfficeID) and destination branch (ToOfficeID) cannot be identical."
//             });
//         }

//         // 1. SAFETY CHECK: Verify the source warehouse has enough physical stock
//         const [stockCheck] = await db.query(
//             'SELECT Quantity FROM stockmaster WHERE item = ? AND officeId = ? AND Quantity >= ? LIMIT 1', 
//             [itemName, sourceOffice, parseInt(qty)]
//         );
        
//         if (stockCheck.length === 0) {
//             return res.status(400).json({ success: false, message: "Transaction blocked. Insufficient available stock at source branch." });
//         }

       

//         // ==========================================
//         // CASE 1: HANDING ASSET DIRECTLY TO AN EMPLOYEE
//         // ==========================================
//         if (issueType === 'employee') {
//             // const [stockRow] = await db.query('SELECT id FROM stockmaster WHERE item = ? AND officeId = ? LIMIT 1', [itemName, sourceOffice]);
//             // await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?', [parseInt(qty), stockRow[0].id]);

//             // await db.query(`
//             //     INSERT INTO issuemaster 
//             //         (EmpID, name, issue_type, OfficeID, OfficeCode, Item, Quantity, status, DateTime) 
//             //     VALUES (?, ?, 'employee', ?, 'NI', ?, ?, 'completed', NOW())
//             // `, [empId, empName, sourceOffice, itemName, parseInt(qty)]);

//             // return res.status(200).json({ success: true, message: `Successfully distributed ${qty} units to Employee ID: ${empId}` });

//              const [empProfile] = await db.query(
//                 'SELECT OfficeCode FROM employeemaster WHERE EmpId = ? LIMIT 1', 
//                 [empId]
//             );

//             if (empProfile.length === 0) {
//                 return res.status(404).json({ success: false, message: `Issuance blocked: Employee ID ${empId} is not registered in the system.` });
//             }

//             const finalEmpOfficeCode = empProfile[0].OfficeCode;
//             let finalEmpOfficeId = 861; // Safe internal variable fallback code baseline default

//             // 🔍 Step B: Convert that string code into a numeric ID using your office index mapping table
//             const [officeProfile] = await db.query(
//                 'SELECT OfficeID FROM officemaster WHERE OfficeCode = ? LIMIT 1',
//                 [finalEmpOfficeCode]
//             );
//             if (officeProfile.length > 0) {
//                 finalEmpOfficeId = officeProfile[0].OfficeID;
//             }

//             // 📉 Step C: Deduct physical stock from the ADMIN's warehouse immediately
//             const [stockRow] = await db.query('SELECT id FROM stockmaster WHERE item = ? AND officeId = ? LIMIT 1', [itemName, sourceOffice]);
//             await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?', [parseInt(qty), stockRow[0].id]);

//             // 📝 Step D: Save direct delivery record trace tracking data into your issuemaster table
//             await db.query(`
//                 INSERT INTO issuemaster 
//                     (EmpID, name, issue_type, OfficeID, OfficeCode, Item, Quantity, status, DateTime) 
//                 VALUES (?, ?, 'employee', ?, ?, ?, ?, 'completed', NOW())
//             `, [empId, empName, finalEmpOfficeId, finalEmpOfficeCode, itemName, parseInt(qty)]);

//             return res.status(200).json({ 
//                 success: true, 
//                 message: `Successfully distributed ${qty} units of ${itemName} from Office ${sourceOffice} to Employee ${empId} (Home Branch: ${finalEmpOfficeCode})` 
//             });
//         }
            
//         // ==========================================
//         // CASE 2: SHIPPING INTER-BRANCH FREIGHT BALANCES
//         // ==========================================
//          else if (issueType === 'branch') {
//             if (!itemId) {
//                 return res.status(400).json({ success: false, message: "Item catalog definition missing from master directory." });
//             }

//             const batchId = `Batch_${Math.floor(1000000000 + Math.random() * 9000000000)}`;

//             // Using the verified destinationOffice variable here
//             await db.query(`
//                 INSERT INTO stocktransfer 
//                     (BatchId, FromOfficeID, ToOfficeID, Item, Quantity, ModeOfTransfer, Status, Date) 
//                 VALUES (?, ?, ?, ?, ?, ?, 'Pending', NOW())
//             `, [batchId, sourceOffice, destinationOffice, itemId, parseInt(qty), modeOfTransfer || 'By Hand']);

//             return res.status(200).json({ 
//                 success: true, 
//                 message: `Freight transfer logged into stocktransfer table under ${batchId}! Standing by for destination branch acceptance.` 
//             });
//         }

//         return res.status(400).json({ success: false, message: "Invalid issuance operational parameters passed." });
//     } catch (error) {
//         return res.status(500).json({ success: false, message: "Asset deployment transaction crashed.", error: error.message });
//     }

// };




/**
 * @desc    Unified Asset Issuance Subsystem Handler
 * @route   POST /api/inventry/issue
 * @access  Protected (Admin / Branch Admin Only)
 */
// export const issueInventoryAsset = async (req, res) => {
//     // 🎯 Frontend transmits explicit numeric database IDs under the hood for Office variables
//     const { 
//         issueType,       // 'employee' OR 'branch'
//         itemName,        // Exact nomenclature string from itemmaster
//         qty,             // Numeric count of assets to deploy
//         empId,           // Mandatory string if issueType === 'employee'
//         empName,         // Optional string string if issueType === 'employee'
//         FromOfficeID,    // Numeric source warehouse ID (e.g., 1)
//         ToOfficeID,      // Numeric target warehouse ID (Mandatory if issueType === 'branch')
//         modeOfTransfer   // Optional string tracking parameter (e.g. 'By Road', 'Courier')
//     } = req.body;

//     const sourceOffice = FromOfficeID || 1;
//     const destinationOffice = ToOfficeID;
//     const transferQty = parseInt(qty);

//     // Basic structural validation check
//     if (!itemName || !transferQty || transferQty <= 0) {
//         return res.status(400).json({ 
//             success: false, 
//             message: "Validation Error: Invalid product criteria selection or quantity value passed." 
//         });
//     }

//     try {
//         // Initialize ACID transaction pipeline isolation thread to avoid multi-user dirty reads
//         await db.query('START TRANSACTION');

//         // 1. DIRECT PRODUCT IDENTIFIER RESOLUTION LOOKUP
//         const [itemLookup] = await db.query('SELECT id FROM itemmaster WHERE name = ? LIMIT 1', [itemName]);
//         if (itemLookup.length === 0) {
//             await db.query('ROLLBACK');
//             return res.status(404).json({ 
//                 success: false, 
//                 message: `Validation Error: Selected product model '${itemName}' does not exist in the master directory.` 
//             });
//         }

//         // 2. STOCK LEVEL INTEGRITY AUDIT (Row locked for current session to prevent race conditions)
//         const [stockCheck] = await db.query(
//             'SELECT id, Quantity FROM stockmaster WHERE item = ? AND officeId = ? FOR UPDATE', 
//             [itemName, sourceOffice]
//         );
        
//         if (stockCheck.length === 0 || stockCheck[0].Quantity < transferQty) {
//             await db.query('ROLLBACK');
//             return res.status(400).json({ 
//                 success: false, 
//                 message: `Transaction Aborted: Insufficient stock pool for '${itemName}' at the source branch warehouse.` 
//             });
//         }

//         const currentStockRecordId = stockCheck[0].id;

//         // ==========================================
//         // PIPELINE CASE A: ALLOCATING ASSET TO AN EMPLOYEE
//         // ==========================================
//         if (issueType === 'employee') {
//             if (!empId) {
//                 await db.query('ROLLBACK');
//                 return res.status(400).json({ success: false, message: "Validation Error: Employee unique database key code ID is missing." });
//             }

//             // Verify staff node exists in the personnel directory table
//             const [empProfile] = await db.query(
//                 'SELECT OfficeCode FROM employeemaster WHERE EmpId = ? LIMIT 1', 
//                 [empId]
//             );

//             if (empProfile.length === 0) {
//                 await db.query('ROLLBACK');
//                 return res.status(404).json({ success: false, message: `Issuance blocked: Staff reference identifier ${empId} is not registered.` });
//             }

//             const finalEmpOfficeCode = empProfile[0].OfficeCode;
//             let finalEmpOfficeId = sourceOffice; // Fallback mapping match

//             // Resolve the employee's structural location name code into its numeric primary key
//             const [officeProfile] = await db.query(
//                 'SELECT OfficeID FROM officemaster WHERE OfficeCode = ? LIMIT 1',
//                 [finalEmpOfficeCode]
//             );
//             if (officeProfile.length > 0) {
//                 finalEmpOfficeId = officeProfile[0].OfficeID;
//             }

//             // 📉 Step 1: Deduct current balance stock immediately from the issuing source warehouse
//             await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?', [transferQty, currentStockRecordId]);

//             // 📝 Step 2: Log asset lifecycle deployment out into the final completed issuemaster sheet
//             await db.query(`
//                 INSERT INTO issuemaster 
//                     (EmpID, name, issue_type, OfficeID, OfficeCode, Item, Quantity, status, DateTime) 
//                 VALUES (?, ?, 'employee', ?, ?, ?, ?, 'completed', NOW())
//             `, [empId, empName || 'Staff Member', finalEmpOfficeId, finalEmpOfficeCode, itemName, transferQty]);

//             await db.query('COMMIT');
//             return res.status(200).json({ 
//                 success: true, 
//                 message: `Asset deployed successfully. ${transferQty} unit(s) of ${itemName} issued to Employee ${empId} and deducted from local warehouse.` 
//             });
//         }
            
//         // ==========================================
//         // PIPELINE CASE B: SHIPPING INTER-BRANCH TRANSLATION FREIGHT
//         // ==========================================
//         else if (issueType === 'branch') {
//             if (!destinationOffice) {
//                 await db.query('ROLLBACK');
//                 return res.status(400).json({ success: false, message: "Validation Error: Destinational Target Office location ID parameter is required." });
//             }

//             if (parseInt(sourceOffice) === parseInt(destinationOffice)) {
//                 await db.query('ROLLBACK');
//                 return res.status(400).json({ success: false, message: "Validation Error: Internal branch self-transfers are structurally blocked." });
//             }

//             const uniqueBatchTrackingCode = `Batch_${Math.floor(1000000000 + Math.random() * 9000000000)}`;

//             // 📉 Step 1: Deduct physical inventory allotment immediately from source warehouse to prevent double-spending in transit
//             await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?', [transferQty, currentStockRecordId]);

//             // 📝 Step 2: Push tracking details into transit shipping log ledger set to 'Pending'
//             // Using exact nomenclature string matching for query consistency
//             await db.query(`
//                 INSERT INTO stocktransfer 
//                     (BatchId, FromOfficeID, ToOfficeID, Item, Quantity, ModeOfTransfer, Status, Date) 
//                 VALUES (?, ?, ?, ?, ?, ?, 'Pending', NOW())
//             `, [uniqueBatchTrackingCode, sourceOffice, destinationOffice, itemName, transferQty, modeOfTransfer || 'By Hand']);

//             await db.query('COMMIT');
//             return res.status(200).json({ 
//                 success: true, 
//                 message: `Inter-branch transfer initialized. Batch logged under ${uniqueBatchTrackingCode}. Stock balance dropped at source and set to transit status.` 
//             });
//         }

//         // Catch-all safety fallback trigger
//         await db.query('ROLLBACK');
//         return res.status(400).json({ success: false, message: "Invalid issuance configuration type query string passed." });

//     } catch (error) {
//         await db.query('ROLLBACK');
//         console.error("Critical Runtime Failure inside Issuance Endpoint:", error.message);
//         return res.status(500).json({ 
//             success: false, 
//             message: "Internal server hardware transaction crashed.", 
//             error: error.message 
//         });
//     }
// };

// export const acceptBranchTransfer = async (req, res) => {

//     const { transferId } = req.body; // Passing the unique integer ID from the stocktransfer row

//     try {
//         // A. Search your stocktransfer table for the pending shipment row entry
//         const [transferRecords] = await db.query(
//             'SELECT * FROM stocktransfer WHERE ID = ? AND Status = "Pending" LIMIT 1',
//             [transferId]
//         );

//         if (transferRecords.length === 0) {
//             return res.status(404).json({ success: false, message: "No active pending freight records located matching this Transfer index ID." });
//         }

//         const transfer = transferRecords[0];
//         const { Item: itemId, Quantity: qty, FromOfficeID: originBranch, ToOfficeID: targetBranch } = transfer;

//         // B. TRANSLATE ID BACK TO TEXT NAME: Get the string representation for stockmaster updates
//         const [nameLookup] = await db.query('SELECT name FROM itemmaster WHERE id = ? LIMIT 1', [itemId]);
//         if (nameLookup.length === 0) {
//             return res.status(400).json({ success: false, message: "Internal tracking error: Item string name resolution mapping failed." });
//         }
//         const itemName = nameLookup[0].name;

//         // C. Confirm origin warehouse branch still holds the quantity
//         const [originStock] = await db.query(
//             'SELECT id, Quantity FROM stockmaster WHERE item = ? AND officeId = ? LIMIT 1',
//             [itemName, originBranch]
//         );

//         if (originStock.length === 0 || originStock[0].Quantity < qty) {
//             return res.status(400).json({ success: false, message: "Acceptance failed. Releasing branch no longer holds sufficient units." });
//         }

//         // D. ATOMIC SHUFFLE: Deduct from origin source warehouse
//         await db.query(
//             'UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?',
//             [parseInt(qty), originStock[0].id]
//         );

//         // E. ATOMIC SHUFFLE: Deposit directly into receiving target warehouse destination room
//         const [targetStockCheck] = await db.query(
//             'SELECT id FROM stockmaster WHERE item = ? AND officeId = ? LIMIT 1',
//             [itemName, targetBranch]
//         );

//         if (targetStockCheck.length > 0) {
//             await db.query(
//                 'UPDATE stockmaster SET Quantity = Quantity + ? WHERE id = ?',
//                 [parseInt(qty), targetStockCheck[0].id]
//             );
//         } else {
//             await db.query(
//                 'INSERT INTO stockmaster (officeId, item, Quantity, UpdateDateTime) VALUES (?, ?, ?, NOW())',
//                 [targetBranch, itemName, parseInt(qty)]
//             );
//         }

//         // F. CLOSE OUT LEDGER: Update transfer status field index indicator label string to 'Delivered'
//         await db.query('UPDATE stocktransfer SET Status = "Delivered" WHERE ID = ?', [transferId]);

//         return res.status(200).json({
//             success: true,
//             message: `Freight ledger row ${transferId} closed successfully. Shifted ${qty} units of "${itemName}" from Branch ${originBranch} to Branch ${targetBranch}.`
//         });

//     } catch (error) {
//         return res.status(500).json({ success: false, message: "Acceptance execution crashed.", error: error.message });
//     }
// };


export const issueInventoryAsset = async (req, res) => {

    console.log("📥 BACKEND RECEIVED REQ.BODY:", req.body);
    const { 
        issueType,       // 'employee' OR 'branch'
        itemName,        // Exact nomenclature string name matching itemmaster
        qty,             // Numeric count of items to move
        empId,           // Mandatory string if issueType === 'employee'
        empName,         // Optional string if issueType === 'employee'
        FromOfficeID,    // Source office ID (defaults to 1)
        ToOfficeID,      // Target warehouse ID if issueType === 'branch'
        CourierName,   // 🌟 ADD THIS SPECIFIC PARAMETER
        DocketNumber,
        modeOfTransfer   
    } = req.body;

    const sourceOffice = FromOfficeID || 1;
    const transferQty = parseInt(qty);

    

    if (!itemName || !transferQty || transferQty <= 0) {
        return res.status(400).json({ 
            success: false, 
            message: "Validation Error: Invalid criteria configuration selection or quantal volume passed." 
        });
    }

    try {
        // Start isolation transaction pipeline thread
        await db.query('START TRANSACTION');

        // 1. PRODUCT DIRECTORY LOOKUP
        const [itemLookup] = await db.query('SELECT id FROM itemmaster WHERE name = ? LIMIT 1', [itemName]);
        if (itemLookup.length === 0) {
            await db.query('ROLLBACK');
            return res.status(404).json({ 
                success: false, 
                message: `Validation Error: Model type '${itemName}' does not exist in master directories.` 
            });
        }
        
        // Save the structural numeric primary key ID for item validation tracking references
        const numericItemId = itemLookup[0].id;

        //  let stockCheckResults = await db.query(
        //     'SELECT id, Quantity FROM stockmaster WHERE item = ? AND officeId = ? AND purchase_no IS NOT NULL ORDER BY Quantity DESC LIMIT 1 FOR UPDATE', 
        //     [itemName, sourceOffice]
        // );



        // let stockCheck = stockCheckResults[0];

//          if (stockCheck.length === 0) {
//          let fallbackResults = await db.query(
//             'SELECT id, Quantity FROM stockmaster WHERE item = ? AND officeId = ? AND purchase_no IS NULL LIMIT 1 FOR UPDATE', 
//             [itemName, sourceOffice]
//         );
//        stockCheck = fallbackResults[0];
//    }


        // 2. STOCK pool INTEGRITY AUDIT (Session row lock)
        // const [stockCheck] = await db.query(
        //     'SELECT id, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no IS NOT NULL ORDER BY Quantity DESC LIMIT 1 FOR UPDATE', 
        //     [itemName, sourceOffice]
        // );

        // let stockCheck = stock

        //  if (stockCheck.length === 0) {
        //     [stockCheck] = await db.query(
        //         'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no IS NULL LIMIT 1 FOR UPDATE', 
        //         [itemName, sourceOffice]
        //     );
        // }
        
        
          const [purchasedStock] = await db.query(
            'SELECT COALESCE(SUM(Quantity), 0) AS totalBought FROM stockmaster WHERE item = ? AND officeId = ?',
            [itemName, sourceOffice]
        );

        // Sum up all incoming items accepted from other branches
        const [inboundStock] = await db.query(
            "SELECT COALESCE(SUM(Quantity), 0) AS totalInbound FROM stocktransfer WHERE Item = ? AND ToOfficeID = ? AND Status = 'Accepted' ",
            [numericItemId, sourceOffice]
        );

        // Sum up all outgoing items currently sent out (Pending or Accepted, but not Rejected)
        const [outboundStock] = await db.query(
            "SELECT COALESCE(SUM(Quantity), 0) AS totalOutbound FROM stocktransfer WHERE Item = ? AND FromOfficeID = ? AND Status != 'Rejected' ",
            [numericItemId, sourceOffice]
        );

        const totalBought = parseInt(purchasedStock[0].totalBought || 0);
        const totalInbound = parseInt(inboundStock[0].totalInbound || 0);
        const totalOutbound = parseInt(outboundStock[0].totalOutbound || 0);

        // Calculate actual net mathematical balance
        const netAvailableStock = (totalBought + totalInbound) - totalOutbound;

        // Integrity audit pool validation check
        if (netAvailableStock < transferQty) {
            await db.query('ROLLBACK');
            return res.status(400).json({ 
                success: false, 
                message: `Transaction Aborted: Insufficient stock pool balance for '${itemName}'. Available: ${netAvailableStock} Units.` 
            });
        }







        // if (stockCheck.length === 0 || stockCheck[0].Quantity < transferQty) {
        //     await db.query('ROLLBACK');
        //     return res.status(400).json({ 
        //         success: false, 
        //         message: `Transaction Aborted: Insufficient stock pool balance for '${itemName}' at the source branch warehouse.` 
        //     });
        // }

        // const currentStockRecordId = stockCheck[0].id;

        // ====================================================================
        // PIPELINE PIPELINE TRACK A: ALLOCATING INTRA-COMPANY ASSET TO A WORKER
        // ====================================================================
        if (issueType === 'employee') {
            if (!empId) {
                await db.query('ROLLBACK');
                return res.status(400).json({ success: false, message: "Validation Error: Employee selection reference identifier code missing." });
            }

            // Read the employee node parameters from directory log tables
            const [empProfile] = await db.query(
                'SELECT OfficeCode FROM employeemaster WHERE EmpId = ? OR id = ? LIMIT 1', 
                [empId, empId]
            );

            if (empProfile.length === 0) {
                await db.query('ROLLBACK');
                return res.status(404).json({ success: false, message: `Issuance Blocked: Target worker reference #${empId} is unregistered.` });
            }

            // const finalEmpOfficeCode = empProfile[0].OfficeCode;
            // let finalEmpOfficeId = sourceOffice;

            // // Resolve alphanumeric office designation code string values to numeric relational table primary keys
            // const [officeProfile] = await db.query(
            //     'SELECT OfficeID, OfficeName FROM officemaster WHERE OfficeCode = ? OR OfficeName LIKE ? LIMIT 1',
            //     [finalEmpOfficeCode, `%${finalEmpOfficeCode}%`]
            // );
            // if (officeProfile.length > 0) {
            //     finalEmpOfficeId = officeProfile[0].OfficeID;
            // }

            // 📉 Step 1: Deduct from stockmaster storage rows immediately
            // await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE id = ?', [transferQty, currentStockRecordId]);

            // 📝 Step 2: Push transaction reference into historical audit tracking sheet tables
            await db.query(`
                INSERT INTO issuemaster 
                    (EmpID, name, issue_type, OfficeID, Item, Quantity, status, DateTime) 
                VALUES (?, ?, 'employee', ?, ?, ?, 'completed', NOW())
            `, [empId, empName || 'Staff Member', parseInt(ToOfficeID),  itemName, transferQty]);

            await db.query('COMMIT');
            return res.status(200).json({ 
                success: true, 
                message: `Asset deployed successfully. ${transferQty} unit(s) of ${itemName} issued to Employee ${empId} and deducted from stockmaster.` 
            });
        }
            
        // ====================================================================
        // PIPELINE PIPELINE TRACK B: SHIPPING FREIGHT MANIFEST INTER-BRANCH TRANSIT LOG
        // ====================================================================
        else if (issueType === 'branch') {
            if (!ToOfficeID) {
                await db.query('ROLLBACK');
                return res.status(400).json({ success: false, message: "Validation Error: Target target destination office primary key parameter required." });
            }

            if (parseInt(sourceOffice) === parseInt(ToOfficeID)) {
                await db.query('ROLLBACK');
                return res.status(400).json({ success: false, message: "Validation Error: Circular branch self-transfers are structurally blocked." });
            }

            const uniqueBatchTrackingCode = `Batch_${Math.floor(1000000000 + Math.random() * 9000000000)}`;

            // 📉 Step 1: Deduct from stockmaster location row immediately
            // await db.query('UPDATE stockmaster SET Quantity = Quantity - ? WHERE Id = ?', [transferQty, currentStockRecordId]);

            // 📝 Step 2: Push tracking details into stocktransfer log ledger set to 'Pending'
            // 🎯 HIGHLIGHT CHANGE: We save the item's numeric ID instead of a plain string name row field

            //   const safeEmpIdForDb = req.user?.EmpId || req.user?.id || req.user?.ID || "SYSTEM";

            // Safe explicit session tracking id
            const safeSessionEmpId = req.user?.EmpId || req.user?.id || req.user?.ID || "SYSTEM";
            
            await db.query(`
                INSERT INTO stocktransfer 
                    (BatchId, FromOfficeID, ToOfficeID, Item, Quantity, ModeOfTransfer, CourierName, DocketNumber, Status, Date) 
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'Pending', NOW())
            `, [uniqueBatchTrackingCode, sourceOffice, ToOfficeID, numericItemId, transferQty, modeOfTransfer || 'By Hand', safeSessionEmpId, req.body.CourierName || req.body.courierName || '', req.body.DocketNumber || req.body.docketNumber || '']);

            await db.query('COMMIT');
            return res.status(200).json({ 
                success: true, 
                message: `Inter-branch transfer initialized. Batch logged under ${uniqueBatchTrackingCode}. Stock balance dropped at source and set to transit status.` 
            });
        }

        await db.query('ROLLBACK');
        return res.status(400).json({ success: false, message: "Invalid configuration type query criteria parameter structure string passed." });

    } catch (error) {
        await db.query('ROLLBACK');
        console.error("Critical Runtime Failure inside Issuance Endpoint:", error.message);
        return res.status(500).json({ success: false, message: "Internal server hardware transaction crashed.", error: error.message });
    }
};

export const getInventoryTransfers = async (req, res) => {
    try {
        // 🎯 FIX: Changed 'o1.OfficeID' and 'o2.OfficeID' to match your column conventions ('officeId' / 'id')
        const queryStr = `
            SELECT 
                st.id,
                st.BatchId,
                st.FromOfficeID,
                o1.OfficeName AS FromOfficeName,
                st.ToOfficeID,
                o2.OfficeName AS ToOfficeName,
                st.Item AS ItemId,
                im.name AS item, 
                st.Quantity,
                st.ModeOfTransfer,
                st.CourierName,
                st.DocketNumber,
                st.CourierDate,
                st.Status,
                st.Date
            FROM stocktransfer st
            LEFT JOIN officemaster o1 ON st.FromOfficeID = o1.id  -- Or use o1.officeId if 'id' fails
            LEFT JOIN officemaster o2 ON st.ToOfficeID = o2.id  -- Or use o2.officeId if 'id' fails
            LEFT JOIN itemmaster im ON st.Item = im.id
            ORDER BY st.Date DESC
        `;

        const [transfers] = await db.query(queryStr);

          console.group("🛢️ BACKEND OUTBOUND FREIGHT MANIFEST DUMP");
            console.log("Total Rows Loaded:", transfers.length);
            if (transfers.length > 0) {
                // Look at the relationship values of the very first row
                console.log("Row 0 Relationship Proof -> ID:", transfers[0].id, " | FromOfficeID:", transfers[0].FromOfficeID, " | ToOfficeID:", transfers[0].ToOfficeID);
            }
            console.groupEnd();
 
        return res.status(200).json({
            success: true,
            transfers: transfers
        });

    } catch (error) {
        console.error("Critical Failure inside getInventoryTransfers Endpoint:", error.message);
        return res.status(500).json({ 
            success: false, 
            message: "Internal server error fetching logistics logs.",
            error: error.message 
        });
    }
};


/**
 * @desc    Confirm and finalize an inter-branch stock transfer
 * @route   POST /api/inventry/accept
 * @access  Protected (Admin / Branch Admin Only)
 */
export const acceptBranchTransfer = async (req, res) => {
    const { batchId } = req.body; // Transmitted from frontend action

    if (!batchId) {
        return res.status(400).json({ 
            success: false, 
            message: "Validation Error: Unique BatchId tracking code parameter is required." 
        });
    }

    try {

        // 🟢 DYNAMIC USER RESOLUTION: Resolves who is running the acceptance action right now
        const loggedInUserId = 
            req.user?.EmpId ||  
            req.user?.id ||     
            req.user?.ID ||     
            1;

        // Initialize ACID transaction thread to ensure all stock changes lock atomically
        await db.query('START TRANSACTION');

        // 1. VERIFY SHIPMENT: Find the transit log record and lock it for update
        const [transferRows] = await db.query(
            'SELECT FromOfficeID, ToOfficeID, Item, Quantity, Status FROM stocktransfer WHERE BatchId = ? FOR UPDATE',
            [batchId]
        );

        if (transferRows.length === 0) {
            await db.query('ROLLBACK');
            return res.status(404).json({ success: false, message: `Freight shipment batch code '${batchId}' not found.` });
        }

        const { ToOfficeID, Item, Quantity, Status } = transferRows[0];
        const transferQty = parseInt(Quantity);



        // const userRole = (req.user?.role || '').toLowerCase();
        // if (userRole === 'branch admin' && parseInt(req.user?.officeId) !== parseInt(ToOfficeID)) {
        //     await db.query('ROLLBACK');
        //     return res.status(403).json({
        //         success: false,
        //         message: "Access Denied. You can only accept transfers addressed to your own branch."
        //     });
        // }

           const loggedInOfficeId = parseInt(req.user?.officeId || req.user?.OfficeID);

            if (loggedInOfficeId !== parseInt(ToOfficeID)) {
                await db.query('ROLLBACK');
                return res.status(403).json({
                    success: false,
                    message: `Access Denied. Your office ID (${loggedInOfficeId}) does not match the destination facility ID (${ToOfficeID}) for this shipment.`
                });
            }

        // Safety check: Prevent double-processing an already completed or rejected shipment
        if (Status !== 'Pending') {
            await db.query('ROLLBACK');
            return res.status(400).json({ 
                success: false, 
                message: `Transaction Aborted: This transfer batch has already been processed with status: '${Status}'.` 
            });
        }

        // / /stores the name string (e.g. "BOAT HEADPHONE"). Inserting the raw numeric ID
        // into stockmaster caused item name "13" to appear instead of the real name.
        // Resolve it here before any stockmaster operation.
        const [itemLookup] = await db.query(
            'SELECT name FROM itemmaster WHERE id = ? LIMIT 1',
            [Item]
        );
 
        if (itemLookup.length === 0) {
            await db.query('ROLLBACK');
            return res.status(400).json({ 
                success: false, 
                message: "Item name resolution failed — item ID not found in master directory." 
            });
        }
 
        const resolvedItemName = itemLookup[0].name;


        // 2. STOCKMASTER BALANCING: Check if the receiving warehouse already holds this item category row
        // const [destStockCheck] = await db.query(
        //     'SELECT id, Quantity FROM stockmaster WHERE item = ? AND OfficeId = ? AND purchase_no IS NULL FOR UPDATE',
        //     // [Item, ToOfficeID]

        //     [resolvedItemName, ToOfficeID]
        // );


        //  # Insert part 
        // await db.query(
        //     `INSERT INTO stockmaster 
        //         (item, officeId, Quantity, purchase_no, purchase_date, createdBy, UpdateDateTime) 
        //      VALUES (?, ?, ?, NULL, NULL, ?, NOW())`,
        //     [resolvedItemName, ToOfficeID, transferQty, loggedInUserId]
        // );
        // ---------




        // if (destStockCheck.length > 0) {
        //     // Case A: Branch already has an existing row pool -> Add quantities together
        //     await db.query(
        //         'UPDATE stockmaster SET Quantity = Quantity + ? WHERE id = ?',
        //         [transferQty, destStockCheck[0].id]
        //     );
        // } else {
        //     // Case B: Branch has never held this item class model -> Insert a completely fresh row mapping
        //     await db.query(
        //         // 'INSERT INTO stockmaster (item, officeId, Quantity, status) VALUES (?, ?, ?, "active")',
        //           'INSERT INTO stockmaster (item, officeId, Quantity, purchase_no, purchase_date) VALUES (?, ?, ?, NULL, NULL)',
        //         // [Item, ToOfficeID, transferQty]
        //         [resolvedItemName, ToOfficeID, transferQty]
        //     );
        // }

           
        const transferTrackingCode = `TRANSFER_${batchId}`;
        // const safeSessionEmpId = req.user?.EmpId || req.user?.id || req.user?.ID || "SYSTEM";

        console.log("✈️ INSERTING TO STOCKMASTER:", {
            item: resolvedItemName,
            officeId: ToOfficeID,
            Quantity: transferQty,
            source_type: 'transfer',
            purchase_no: transferTrackingCode
        });

        await db.query(
            `INSERT INTO stockmaster 
                (item, officeId, Quantity, source_type, purchase_no, purchase_date, unit_cost,  createdBy, UpdateDateTime) 
             VALUES (?, ?, ?, 'transfer', ?, NULL, 0.00, ?, NOW())`,
            [resolvedItemName, ToOfficeID, transferQty, transferTrackingCode, loggedInUserId]
        );


        // 3. LEDGER RECORD UPDATE: Transition the transit log status flag permanently to 'Accepted'
        await db.query(
            "UPDATE stocktransfer SET Status = 'Accepted' WHERE BatchId = ?",
            [batchId]
        );

        // Commit all changes simultaneously to the database instance
        await db.query('COMMIT');

        return res.status(200).json({ 
            success: true, 
            message: `Inventory successfully processed! Batch ${batchId} claimed. ${transferQty} unit(s) added to destination Office ID: ${ToOfficeID}.` 
        });

    } catch (error) {
        // Rollback and reverse database changes if the backend encounters a structural crash mid-execution
        await db.query('ROLLBACK');
        console.error("Critical Failure inside Acceptance Subsystem:", error.message);
        return res.status(500).json({ 
            success: false, 
            message: "Internal database server transaction error during branch receipt confirmation.", 
            error: error.message 
        });
    }
};

export const rejectBranchTransfer = async (req, res) => {
    const { batchId } = req.body;
 
    if (!batchId) {
        return res.status(400).json({ 
            success: false, 
            message: "Validation Error: Unique BatchId tracking code parameter is required." 
        });
    }
 
    try {
        await db.query('START TRANSACTION');
 
        // 1. Find the transfer and lock it
        const [transferRows] = await db.query(
            'SELECT FromOfficeID, ToOfficeID, Item, Quantity, Status FROM stocktransfer WHERE BatchId = ? FOR UPDATE',
            [batchId]
        );
 
        if (transferRows.length === 0) {
            await db.query('ROLLBACK');
            return res.status(404).json({ 
                success: false, 
                message: `Freight shipment batch code '${batchId}' not found.` 
            });
        }
 
        const { FromOfficeID, ToOfficeID, Item, Quantity, Status} = transferRows[0];
        const transferQty = parseInt(Quantity);
 
        // 2. Only Pending transfers can be rejected
        if (Status !== 'Pending') {
            await db.query('ROLLBACK');
            return res.status(400).json({ 
                success: false, 
                message: `Transaction Aborted: This transfer has already been processed with status: '${Status}'.` 
            });
        }
 
        // 3. Office-scoped permission check — same as acceptBranchTransfer.
        // Branch admin can only reject transfers addressed to their own office.
        // Global admin bypasses this restriction.
        const userRole = (req.user?.role || '').toLowerCase();
        if (userRole === 'branch admin' && parseInt(req.user?.officeId) !== parseInt(ToOfficeID)) {
            await db.query('ROLLBACK');
            return res.status(403).json({
                success: false,
                message: "Access Denied. You can only reject transfers addressed to your own branch."
            });
        }
 
        const [itemLookup] = await db.query(
            'SELECT name FROM itemmaster WHERE id = ? LIMIT 1',
            [Item]
        );
 
        if (itemLookup.length === 0) {
            await db.query('ROLLBACK');
            return res.status(400).json({ 
                success: false, 
                message: "Item name resolution failed — item ID not found in master directory." 
            });
        }
 
        const resolvedItemName = itemLookup[0].name;




        // 4. CREDIT STOCK BACK TO SOURCE OFFICE.
        // When a transfer was created, stock was immediately deducted from FromOfficeID.
        // On rejection, we reverse that deduction — the items physically never left
        // or are being returned, so the source warehouse balance must be restored.
        
            // 'SELECT id FROM stockmaster WHERE item = ? AND purchase_no IS NULL officeId = ? FOR UPDATE',
            // [Item, FromOfficeID]

            // 'SELECT id, Quantity FROM stockmaster WHERE Item = ? AND purchase_no IS NULL AND OfficeId = ? FOR UPDATE',


             // =========================================================================
        // 🎯 Previous working part rn commented if need will uncomment 
        // =========================================================================


        //      let sourceStockCheck;
        //       if (purchase_no) {
        //        [sourceStockCheck] = await db.query(
        //         'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no = ? FOR UPDATE',
        //         [resolvedItemName, FromOfficeID, purchase_no]
        //     );
        // } else{
            
        //     // const [sourceStockCheck] = await db.query(
                    
        //             // 'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND purchase_no IS NULL AND OfficeId = ? FOR UPDATE',
                     
        //             [sourceStockCheck] = await db.query( 
        //              'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no IS NULL FOR UPDATE',

        //             [resolvedItemName, FromOfficeID]
        //     );
 
        // }

  // =========================================================================
        // 🎯 Previous working part rn commented if need will uncomment 
        // =========================================================================
         
        // =========================================================================
        // 🎯 HIGHLIGHTED CHANGE #5: TWO-STEP ROUTING FALLBACK (FIXES THE BLANK LINES SPLITTING)
        // =========================================================================
        // First Priority check: Look for any active Direct Purchase Order Row
        // let [sourceStockCheck] = await db.query(
        //     'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no IS NOT NULL LIMIT 1 FOR UPDATE',
        //     [resolvedItemName, FromOfficeID]
        // );
 
        // Second Priority check: Fallback to internal transfer tracking lines if no direct purchase row is active
        // if (sourceStockCheck.length === 0) {
        //     [sourceStockCheck] = await db.query(
        //         'SELECT ID, Quantity FROM stockmaster WHERE Item = ? AND OfficeId = ? AND purchase_no IS NULL LIMIT 1 FOR UPDATE',
        //         [resolvedItemName, FromOfficeID]
        //     );
        // }
         



           
        // if (sourceStockCheck.length > 0) {
        //     // Row exists — add the quantity back

        //    const targetRowId = sourceStockCheck[0].ID !== undefined ? sourceStockCheck[0].ID : sourceStockCheck[0].id;

        //     await db.query(
        //         'UPDATE stockmaster SET Quantity = Quantity + ? WHERE ID = ?',
               
        //           [transferQty, targetRowId]

        //     );
        // } else {
           
        //     await db.query(
        //         'INSERT INTO stockmaster (Item, OfficeId, Quantity, purchase_no, purchase_date) VALUES (?, ?, ?, NULL, NULL)',
        //         [resolvedItemName, FromOfficeID, transferQty]
        //     );
        // }
 
        // 5. Mark transfer as Rejected
        await db.query(
            "UPDATE stocktransfer SET Status = 'Rejected' WHERE BatchId = ?",
            [batchId]
        );
 
        await db.query('COMMIT');
 
        return res.status(200).json({ 
            success: true, 
            message: `Transfer ${batchId} rejected. ${transferQty} unit(s) credited back to source Office ID: ${FromOfficeID}.` 
        });
 
    } catch (error) {
        await db.query('ROLLBACK');
        console.error("Critical Failure inside Rejection Subsystem:", error.message);
        return res.status(500).json({ 
            success: false, 
            message: "Internal database server transaction error during transfer rejection.",
            error: error.message 
        });
    }
};
 

export const getEmployeeIssuedHistory = async (req, res) => {
    try {
        // Query the raw historical rows inserted under the 'employee' allocation pipeline
        const queryStr = `
            SELECT 
                id,
                EmpID,
                name,
                issue_type,
                OfficeID,
                OfficeCode,
                Item,
                Quantity,
                status,
                DateTime
            FROM issuemaster
            WHERE issue_type = 'employee'
            ORDER BY DateTime DESC
        `;

        const [history] = await db.query(queryStr);

        return res.status(200).json({
            success: true,
            data: history // This fulfills the exact format your frontend expectRes looks for!
        });

    } catch (error) {
        console.error("Failure inside getEmployeeIssuedHistory Endpoint:", error.message);
        return res.status(500).json({ 
            success: false, 
            message: "Internal server error fetching staff allocation history.",
            error: error.message 
        });
    }
};

// Add this to the very bottom of your inventry_controller.js file
export const getBranchStock = async (req, res) => {
    try {
        const { officeId } = req.params; 

        // Query stockmaster to pull items that belong to this specific warehouse office location
        const queryStr = `
            SELECT 
                id,
                item,
                Quantity,
                officeId
            FROM stockmaster
            WHERE officeId = ?
        `;

        const [stockRecords] = await db.query(queryStr, [officeId]);

        return res.status(200).json({
            success: true,
            data: stockRecords
        });

    } catch (error) {
        console.error("Critical Failure inside getBranchStock Controller:", error.message);
        return res.status(500).json({ 
            success: false, 
            message: "Internal server error fetching branch warehouse stock balances.",
            error: error.message 
        });
    }
};



// e.Name as creatorName,